using System;

namespace HarmonyLib
{
	// Token: 0x02000016 RID: 22
	internal class LeaveTry
	{
		// Token: 0x06000066 RID: 102 RVA: 0x00003B6D File Offset: 0x00001D6D
		public override string ToString()
		{
			return "(autogenerated)";
		}
	}
}
